#+TITLE: Mastering Concurrent Processes with core.async

Clojure's core.async library allows you to create multiple independent processes within a single program.

In this chapter, we will learn to use channels to communicate between independent processes created by go blocks and thread, a bit about how Clojure manages threads efficiently with parking and blocking, how to use alts!!, a more straight forward way to creating queues, and how to use process pipelines.

* Getting Started with Processes

At the heart of core.async is the process, a concurrently running unit of logic that responds to events.

#+BEGIN_SRC clojure
;; create a channel called echo-chan
(def echo-chan (chan))
;; create a new process
(go (println (<! echo-chan))) ;; when I take a message from echo-chan, print it
;; put the string "ketchup" on echo-chan & return true
(>!! echo-chan "ketchup")
#+END_SRC

We used the chan function to create a channel called echo-chan. Channels communicate messages. You can put messages on a channel and take messages off of a channel. Processes wait for the completion of put and take -- these are the events that processes respond to.

We can think of processes as having two rules:
1. When trying to put a message on a channel or take a message off of it, wait and do nothing until the put or take succeeds
2. When the put or take succeeds, continue executing

In the second line we used go to create a new process. Everything within the go expression (called a go block) - runs concurrently on a separate thread. Go blocks run your processes on a thread pool that contains a number of threads equal to 2 plus the number of cores on the machine. This means our program doesn't have to create a new thread for each process, so we avoid the overhead of creating threads. 

In the expression (<! echo-chan), <! is the take function. It listens to the channel you give it as an argument, and the process it belongs to waits until another process puts a message on the channel. When <! retrieves a value, the value is returned and the println expression is executed.

The expression >!! echo-chan "ketchup" puts the string "ketchup" on echo-chan and returns true. When we put the message on a channel, the process blocks until another process takes the message. 

** Buffering

Its worth noting that our last part had 2 processes: the one created with go and the REPL. The one created with go waits for something to respond to.

#+BEGIN_SRC clojure
(def echo-buffer (chan 2))
(>!! echo-buffer "ketchup")
(>!! echo-buffer "ketchup")
(>!! echo-buffer "ketchup")
#+END_SRC

In this case, we've created a channel with buffer size 2. This means that we can put two values on the channel without waiting, but putting a 3rd one on means the process will wait until another process takes a value from the channel. 

We can also create sliding buffers with sliding-buffer, which drops values in a first in first out fashion, and dropping buffers with dropping-buffer which discards values in a last-in, first out fashion. Neither of these style of buffers will ever cause >!! to block.

Buffers are just elaborations of the core model: processes are independent, concurrently executing units of logic that respond to events. You create processes with go blocks and communicate events over channels.

** Blocking and Parking

